"""empty message

Revision ID: 3a5ad7e05c2e
Revises: cb45d572b250
Create Date: 2021-06-22 10:23:45.328375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5ad7e05c2e'
down_revision = 'cb45d572b250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.create_unique_constraint(None, 'stocks', ['ticker'])
    op.drop_constraint('users_to_stocks_stocks_id_fkey', 'users_to_stocks', type_='foreignkey')
    op.create_foreign_key(None, 'users_to_stocks', 'stocks', ['stocks_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_to_stocks', type_='foreignkey')
    op.create_foreign_key('users_to_stocks_stocks_id_fkey', 'users_to_stocks', 'stocks', ['stocks_id'], ['ticker'])
    op.drop_constraint(None, 'stocks', type_='unique')
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.drop_column('stocks', 'id')
    # ### end Alembic commands ###
