"""empty message

Revision ID: 4fbd92443310
Revises: 7b3ad4f4097d
Create Date: 2021-06-23 15:26:59.727268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbd92443310'
down_revision = '7b3ad4f4097d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('name', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'name')
    # ### end Alembic commands ###
