"""empty message

Revision ID: da7165138bf2
Revises: c2ee7091c828
Create Date: 2021-06-22 10:48:34.940918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7165138bf2'
down_revision = 'c2ee7091c828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users_to_stocks',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('stocks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stocks_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_to_stocks')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
